spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lialU74ZRKkNuZ1Y
            client-secret: 25b6a271ad25344c873ff5d097d20ecf7ea3b74a
            redirect-uri: http://localhost:9999/oauth2/mycallback
            scope: # 사용자의 어떤 정보를 요청할 것인지.
              - user:email
              - read:user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize # 우리 사이트에서 소셜로그인 요청하면 여기로 리다이렉트
            token-uri: https://github.com/login/oauth/access_token # 위에서 사용자가 응 우리 사이트 정보 공유해줘 하면 github에 보내기 위한 토큰이 발급되고
            user-info-uri: https://api.github.com/user # 토큰 가지고 여기로 요청이 들어가면 해당 사용자의 정보가 나옴.

## 우리 어플리케이션이 어떤 서버의 고객인지 해당 서버를 사용하기 위한 정보를 등록
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: Ov23lialU74ZRKkNuZ1Y
#            clientSecret: 25b6a271ad25344c873ff5d097d20ecf7ea3b74a
#            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#            scope:
#              - user:email
#              - read:user
##    아래는 어떤 서버가 우리에게 서비스를 제공하는지에 대한 정보
#    provider:
#      github:
#        authorization-uri: https://github.com/login/oauth/authorize
#        token-uri: https://github.com/login/oauth/access_token
#        user-info-uri: https://api.github.com/user
#
